### ISSUE TITLE
Recurrences bug in v6.71

### ISSUE THREAD

**Issue by mschout** [SBECK-github/Date-Manip#20]
Release 6.71 of Date::Manip seems to have a bug in recurrences.

This worked prior to v6.71:
```
ParseRecur('0:0:0:0:1*0:0', '1 days ago', '0:0:0:0:-23:59:59', '4 days later');
```

But starting in 6.71, this no longer generates recurrences, and it does not set any error value either.

Bisecting shows this broke in 1204e9368319acccd49b3a65ba37ec859776d416

This breaks the `Log::Dispatch::FileRotate` for example.

**Comment by SBECK-github** [comment]
You're correct.  6.71 fixed a problem with a rare type of recurrence... but ended up introducing a bug for a second type of recurrence.  Sorry about that.

I found and fixed the problem and will release a corrected version today.
