### ISSUE TITLE
TimeZone update request

### ISSUE THREAD

**Issue by SparkeyG** [SBECK-github/Date-Manip#28]
Is is difficult to make a release to upgrade the Olsen TZ database file to 2018e?

**Comment by SBECK-github** [comment]
Version 6.74 (released last December) updated to 2018e.  6.75 has also been released to CPAN to fix a problem.

**Comment by SparkeyG** [comment]
I'm sorry I meant 2018i (Released 2018-12-30).

**Comment by SBECK-github** [comment]
Sorry for not getting this done sooner... I've been swamped.  The next release is coming out in a few days (Mar 1) and will contain the newest TZ data.

**Comment by SparkeyG** [comment]
Can you update to 2019c(Released 2019-09-11)

**Comment by SBECK-github** [comment]
The next Date::Manip release is due on Dec 1.  It will include the most recent TZ data.  I will see if I can get a release out earlier than that, but Dec 1 is the latest it will be out.
