### ISSUE TITLE
No entry in Changes for version 6.79

### ISSUE THREAD

**Issue by perlpunk** [SBECK-github/Date-Manip#31]
https://metacpan.org/source/SBECK/Date-Manip-6.79/Changes
I stumbled upon this while maintaining the perl modules repository for openSUSE.

**Comment by SBECK-github** [comment]
Thanks.  I neglected to generate the new Changes file.  The entry will be fixed in the next release.

**Comment by perlpunk** [comment]
Thanks. Any estimate when the next release will be uploaded?
I think we can't update the module in openSUSE without having a list of changes.
