### ISSUE TITLE
Asia/Muscat Timezone is unrecognized

### ISSUE THREAD

**Issue by zrowitsch-riverbed** [SBECK-github/Date-Manip#40]
Even with v6.89 I see:
`ERROR: Date::Manip unable to determine Time Zone.  GMT will be used. at /usr/local/share/perl5/Date/Manip/DM6.pm line 65.`
`ERROR: Date::Manip unable to determine Time Zone.  GMT will be used. at /usr/local/share/perl5/Date/Manip/DM6.pm line 68.`

**Comment by SBECK-github** [comment]
Can you pull the SBECK-github branch and see if it works correctly for you now?

**Comment by zrowitsch-riverbed** [comment]
This appears to work for me now, thanks!
