### ISSUE TITLE
Some Polish language abbreviations and names don't match Linux equivalents

### ISSUE THREAD

**Issue by davidh2075** [SBECK-github/Date-Manip#41]
I've had some difficulty recognising Polish dates on Linux. It seems to be due to a difference between the abbreviations and one month name in the Date::Manip::Lang file polish.pm and those that Linux uses in date(1) and strftime(3).

I'm wondering if there is a reason for the current values being as they are, or if they could be updated to fix the parsing on Linux.

**Weekdays**
The day abbreviations are currently
```
  day_abb => [
    ['po', 'po.', 'pon.', 'pon'],
    ['wt', 'wt.'],
    ['śr', 'śr.', 'sr.', 'sr'],
    ['cz', 'cz.', 'czw.', 'czw'],
    ['pi', 'pi.'],
    ['so', 'so.'],
    ['ni', 'ni.'],
  ],
```

When I test using those values, I get the following result, and the blank output lines are failed parses:
```
% perl -MDate::Manip -lpe 'Date_Init("Language=Polish", "DateFormat=non-US"); $_=UnixDate(ParseDate($_), "%Y%m%d %T")'
pon 26 wrz 13:11:28 2022 AEST
wto 27 wrz 14:11:28 2022 AEST
śro 28 wrz 15:11:28 2022 AEST
czw 29 wrz 16:11:28 2022 AEST
ptk 30 wrz 17:11:28 2022 AEST
sob 24 wrz 11:11:28 2022 AEST
ndz 25 wrz 12:11:28 2022 AEST
20220926 13:11:28


20220929 16:11:28



%

```

If I update the day abbreviations to these values to allow for the 3-letter abbreviations that Linux uses
```
  day_abb => [
    ['po', 'po.', 'pon.', 'pon'],
    ['wt', 'wt.', 'wto', 'wto.'],
    ['śr', 'śr.', 'sr.', 'sr', 'śro', 'śro.', 'sro.', 'sro'],
    ['cz', 'cz.', 'czw.', 'czw'],
    ['pi', 'pi.', 'ptk', 'ptk.'],
    ['so', 'so.', 'sob', 'sob.'],
    ['ni', 'ni.', 'ndz', 'ndz.'],
  ],
```

and rerun the test, all dates parse:
```
% perl -MDate::Manip -lpe 'Date_Init("Language=Polish", "DateFormat=non-US"); $_=UnixDate(ParseDate($_), "%Y%m%d %T")'    
pon 26 wrz 13:11:28 2022 AEST
wto 27 wrz 14:11:28 2022 AEST
śro 28 wrz 15:11:28 2022 AEST
czw 29 wrz 16:11:28 2022 AEST
ptk 30 wrz 17:11:28 2022 AEST
sob 24 wrz 11:11:28 2022 AEST
ndz 25 wrz 12:11:28 2022 AEST
20220926 13:11:28
20220927 14:11:28
20220928 15:11:28
20220929 16:11:28
20220930 17:11:28
20220924 11:11:28
20220925 12:11:28
%
```

Would those values be acceptable to add to the configuration?

**Months**
The Polish month name for February is configured as 'luty'. Linux uses 'lutego', which is a declension form of luty. 

Could 'lutego' be added as an alternative?

regards - David

**Comment by SBECK-github** [comment]
I have made those changes and they will be in the next release.  If you want to check out the SBECK-github branch and verify that the changes work, that would be great.

**Comment by SBECK-github** [comment]
I'm going to close this.  Please reopen if you see continued problems.

**Comment by davidh2075** [comment]
Sorry for the tardy response. I did test the changes you made to the polish.pm file and they work. In testing it, I realised that I gave you the version from my testing on MacOS (Monterey, 12.5.1). So I've retested individually on MacOS and Linux and included all the language files in the test. I have changes to 8 files. Getting late here, so I'll merge the changes tomorrow and retest the merged changes on both OSs. The changes use the SBECK-github branch as the base.

regards - David

**Comment by davidh2075** [comment]
Sullivan, I've attached 8 files named _\<language\>\_new.pm.txt_. They are the merge of changes required to parse dates on MacOS Monterey 12.5.1 and Oracle Linux Server 7.9. I appended .txt to permit attachment. There are some parse failures I note below.

I've also attached two crude scripts I used to test all the language configuration files, _date-manip-test-macos.sh.txt_ and _date-manip-test-linux.sh.txt_. They aren't ideal tests, as they will fail to parse a date if, for example, either a day abbreviation or a month abbreviation isn't recognised. When all date time elements are recognised, they parse, which is how I used them. I ran both scripts with the final merged language files.

I'm not a speaker of any of these languages, so I simply updated the files to achieve successful parsing, using the strings output by date(1).

Do you know yet what the version number will be that incorporates changes? I'll look for it downstream.

### Explaining the Romanian Tuesday day_name update
I added an entry to the Romanian Tuesday array, the last element below, which both Linux and macOS output as the full day name:
`    ['marți', 'marti', 'marþi', 'marţi'],`
The ț in the first element is U+021B, Latin small letter t with comma below.
The ţ in the last element is U+0163, Latin small letter t with cedilla.
Both are accepted as Tuesday in Romanian, e.g. see [reverso translation of both](https://context.reverso.net/translation/romanian-english/marţi+marți).

### Parse failures
I'm including this section just FYI. None of this is causing me a problem. Just stuff I noticed.
#### Russian on macOS
The standard output of date on macOS fails to parse. It's due to the presence of "r. " and the parentheses around the TZ name in the output below. The blank line is the failed parse. Using a format to eliminate the "r. " and parentheses results in a successful parse.
```
% LANG=ru_RU date
четверг,  6 октября 2022 г. 18:34:30 (AEDT)
% LANG=ru_RU date | perl -I/Users/David/Downloads/Date-Manip-SBECK-github/lib/ -MDate::Manip -lpe 'Date_Init("Language=Russian", "DateFormat=non-US"); $_=UnixDate(ParseDate($_), "%Y%m%d %T")'

% LANG=ru_RU date +"%A, %e %B %Y %T %Z"
четверг,  6 октября 2022 18:35:53 AEDT
% LANG=ru_RU date +"%A, %e %B %Y %T %Z" | perl -I/Users/David/Downloads/Date-Manip-SBECK-github/lib/ -MDate::Manip -lpe 'Date_Init("Language=Russian", "DateFormat=non-US"); $_=UnixDate(ParseDate($_), "%Y%m%d %T")'
20221006 18:36:10
%
```

#### German, Italian and Norwegian on Linux
##### German
The default format doesn’t parse, with or without .UTF-8:
```
$ LANG=de_DE.UTF-8 date --date="2022-01-03 11:00:00"
Mo 3. Jan 11:00:00 AEST 2022
```
 
It appears to be due to the period after the day of the month. This does parse, with or without .UTF-8:
```
$ LANG=de_DE.UTF-8 date --date="2022-01-03 11:00:00" +"%a %e %b %Y %T %Z"
Mo  3 Jan 2022 11:00:00 AEST
```

##### Italian
The default format doesn’t parse, with or without .UTF-8:
```
$ LANG=it_IT.UTF-8 date --date="2022-01-03 11:00:00"
lun  3 gen 2022, 11.00.00, AEST
```
 
It appears to the due to the commas, and I didn't check whether the periods in the time contribute. This does parse, with or without .UTF-8:
```
$ LANG=it_IT.UTF-8 date --date="2022-01-03 11:00:00" +"%a %e %b %Y %T %Z"
lun  3 gen 2022 11:00:00 AEST
```
##### Norwegian
The default format doesn’t parse:
```
$ LANG=no_NO date --date="2022-01-03 11:00:00"
ma. 03. jan. 11:00:00 +1000 2022
```
 
It seems to be due to the period after the day of the month.

UTF-8 seems to output the default LANG (en_AU):
```
$ LANG=no_NO.UTF-8 date --date="2022-01-03 11:00:00"
Mon Jan  3 11:00:00 AEST 2022
```
 
This does parse without .UTF-8:
```
$ LANG=no_NO date --date="2022-01-03 11:00:00" +"%a %e %b %Y %T %Z"
ma.  3 jan. 2022 11:00:00 AEST
```
 
This doesn’t parse with .UTF-8, unless you use English, i.e. `Date_Init("Language=English", "DateFormat=non-US")`:
```
$ LANG=no_NO.UTF-8 date --date="2022-01-03 11:00:00" +"%a %e %b %Y %T %Z"
Mon  3 Jan 2022 11:00:00 AEST
```


### Files
[finnish_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721608/finnish_new.pm.txt)
[french_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721607/french_new.pm.txt)
[norwegian_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721609/norwegian_new.pm.txt)
[polish_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721605/polish_new.pm.txt)
[portugue_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721604/portugue_new.pm.txt)
[romanian_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721603/romanian_new.pm.txt)
[russian_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721602/russian_new.pm.txt)
[turkish_new.pm.txt](https://github.com/SBECK-github/Date-Manip/files/9721601/turkish_new.pm.txt)
[date-manip-test-macos.sh.txt](https://github.com/SBECK-github/Date-Manip/files/9722162/date-manip-test-macos.sh.txt)
[date-manip-test-linux.sh.txt](https://github.com/SBECK-github/Date-Manip/files/9722163/date-manip-test-linux.sh.txt)

**Comment by davidh2075** [comment]
Update: a Russian-speaking colleague provided me the update below to the fields structure in russian.pm to try to fix the parsing of the standard date(1) output due to the "r. " element. It didn't work. I guess it may be because Date::Manip isn't expecting a "years" delta expression in a date-time. In any case, It still required removal of both the "r. " and the parentheses around the TZ name to parse.
```
% diff russian.pm russian_macos_linux.pm
50,51c50,51
<     ['г', 'г.', 'гд', 'год', 'лет', 'лет', 'года'],
<     ['мес', 'мес.', 'месяц', 'месяцев'],
---
>     ['г', 'гд', 'год', 'лет', 'лет', 'года'],
>     ['мес', 'месяц', 'месяцев'],
53c53
<     ['д', 'д.', 'день', 'дней', 'дня'],
---
>     ['д', 'день', 'дней', 'дня'],
55,56c55,56
<     ['мн', 'мин', 'мин.', 'минута', 'минут'],
<     ['с', 'с.', 'сек', 'сек.', 'секунда', 'секунд'],
---
>     ['мн', 'мин', 'минута', 'минут'],
>     ['с', 'сек', 'секунда', 'секунд'],
%
```
