### ISSUE TITLE
Typos: Date::Manip::Date

### ISSUE THREAD

**Issue by mikecappella** [SBECK-github/Date-Manip#49]
VALID TIME ZONE FORMATS
    When specifying a time zone, it can be done in three different ways. One
    way is to specify the actual time zone. The second is to supply a valid
    time zone abbreviation. The third is to specify an offset (with an
    optional abbreviation). The following dates illustrate **the these**
    formats.

The **offset almost never sufficient** to uniquely determine the time zone

**Comment by SBECK-github** [comment]
Thanks for catching that.  It'll be fixed in the next release.
