### ISSUE TITLE
Issue when loading the Module: Use of uninitialized value $zone

### ISSUE THREAD

**Issue by yulivee** [SBECK-github/Date-Manip#9]
Hi,

I am trying to use Date::Manip on AIX 7.2. When performing a "use Date::Manip" I encounter  a whole bunch of error messages:
```

[2]perl_ss@t72:/home/perl_ss $ perl -MDate::Manip -e 0                                         
Use of uninitialized value $zone in lc at /home/perl_ss/perl5/lib/perl5/Date/Manip/TZ.pm line 199.
Use of uninitialized value $zone in concatenation (.) or string at /home/perl_ss/perl5/lib/perl5/Date/Manip/TZ.pm line 1341.
ERROR: [date_period] Invalid zone: 
Use of uninitialized value $z in lc at /home/perl_ss/perl5/lib/perl5/Date/Manip/TZ.pm line 943.
ERROR: Date::Manip unable to determine Time Zone.
ERROR LOADING MODULE: Date::Manip::DM6 at /home/perl_ss/perl5/lib/perl5/Date/Manip.pm line 35.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

I am using Version 6.57 of Date::Manip
```
DB<2> x $Date::Manip::VERSION
0  6.57
```

I am using the DM5 Interface in my scripts.

Is this normal behaviour? It seems odd to me. If you need any further information I will happily provide it.

Cheers,
Sandra

**Comment by SBECK-github** [comment]
I believe that this is the same as a bug that was reported to me a couple weeks ago.  I fixed it and you can download a pre-release at:

http://sullybeck.com/Date-Manip-6.58.tar.gz

Please try it out and see if that fixes your problem.  If not, then I'll look into it further.

**Comment by SBECK-github** [comment]
I haven't heard back, but I believe that this is resolved.  Please reopen if the problem persists.
